
common_bangladeshi_names = [
    "Md", "Md.", "Sk", "Amin", "Emran", "Rana", "Riad", "Shagor", "Kawsar", "Anis", "Ashraf", "Akbar", "Alim", 
    "Arif", "Azim", "Bashir", "Babar", "Badrul", "Baki", "Belal", "Bodi", "Bulbul", "Chowdhury", "Daud", "Dulal", 
    "Emon", "Enamul", "Fahim", "Farhad", "Faisal", "Ferdous", "Gafur", "Gazi", "Habib", "Hasib", "Hasan", "Helal", 
    "Hossain", "Ibrahim", "Imran", "Iqbal", "Ismail", "Jahid", "Jalal", "Jamil", "Jasim", "Kabir", "Kamal", "Karim", 
    "Khaled", "Liton", "Mahi", "Mahfuz", "Mamun", "Manik", "Masud", "Mizan", "Mokbul", "Moin", "Monir", "Mostafa", 
    "Mujib", "Murad", "Nafis", "Naim", "Nasim", "Nazmul", "Niaz", "Noman", "Nur", "Parvez", "Rafiqul", "Rakib", 
    "Rashed", "Razib", "Rezaul", "Sohel", "Riaz", "Ripon", "Rubel", "Sabbir", "Sadiq", "Sajid", "Salam", "Sami", 
    "Sanjib", "Shahid", "Shakib", "Shamsul", "Sharif", "Sohag", "Sumon", "Tariq", "Taufiq", "Touhid", "Wahid", 
    "Yasin", "Zahid", "Zahir", "Zakir", "Zaman", "Zia", "Zubair", "Abdul", "Abid", "Adnan", "Afif", "Ahad", "Ahmad", 
    "Ahsan", "Akash", "Ali", "Alim", "Aminul", "Amzad", "Anik", "Anwar", "Arifur", "Asad", "Ashfaq", "Atiq", "Azhar", 
    "Aziz", "Babu", "Badal", "Basir", "Bijoy", "Bilal", "Chanchal", "Delwar", "Dipu", "Ehsan", "Ershad", "Eshan", 
    "Fakhrul", "Faruq", "Fazle", "Golam", "Hafiz", "Hamid", "Haris", "Hasnat", "Hedayet", "Humayun", "Ilias", 
    "Ishtiaq", "Jabed", "Jafor", "Jamshed", "Johirul", "Junaid", "Kamrul", "Kawsar", "Khalil", "Khorshed", "Lalon", 
    "Latif", "Mahmud", "Majid", "Maksud", "Manjur", "Maruf", "Mazhar", "Mehedi", "Milton", "Minhaj", "Miraz", 
    "Mobarak", "Mohsin", "Morshed", "Muazzam", "Mubin", "Mujibur", "Mustafa", "Nadim", "Nahid", "Nasir", "Nazim", 
    "Niloy", "Nizam", "Noor", "Nure", "Obaid", "Omar", "Pavel", "Rahim", "Rakhat", "Rana", "Rasel", "Rifat", "Riyad", 
    "Rokon", "Ruhul", "Sabit", "Saiful", "Sajjad", "Salim", "Sarwar", "Shafiq", "Shahin", "Shakil", "Shamim", 
    "Shanto", "Sheikh", "Sohail", "Subho", "Tanjil", "Tanvir", "Tipu", "Tuhin", "Uzzal", "Wasim", "Younus", "Zafor", 
    "Zahidul", "Zakaria", "Zamal", "Zulfiqar", "Afsar", "Afzal", "Alam", "Amirul", "Ananta", "Anindya", "Ashik", 
    "Ashim", "Ashraful", "Atikur", "Aynal", "Azad", "Babul", "Bahauddin", "Barkat", "Bashar", "Bokul", "Danish", 
    "Ekram", "Fahad", "Faisal", "Farhan", "Farid", "Fayez", "Ferdous", "Gaziul", "Giyas", "Golam", "Harun", 
    "Hasanuzzaman", "Helal", "Himel", "Hiron", "Hossainul", "Hridoy", "Ibrahim", "Iftekhar", "Imtiaz", "Iqbal", 
    "Ishtiaque", "Jalil", "Jewel", "Jibon", "Kamal", "Kamrul", "Kawser", "Kazi", "Khaledur", "Latifur", "Liton", 
    "Lutfar", "Mahadi", "Mahbub", "Mahdi", "Majed", "Manik", "Maruf", "Masraf", "Masum", "Mazharul", "Mehdi", 
    "Milon", "Mizanur", "Mohammad", "Mohibur", "Moinul", "Mokhlesur", "Monowar", "Morsalin", "Mubarak", "Muhaimin", 
    "Mujahid", "Mustafizur", "Nadim", "Nahiyan", "Najmul", "Nayeem", "Nazir", "Nezam", "Nishat", "Niyaz", "Noorul", 
    "Oli", "Omar", "Parvez", "Rabbani", "Rabbi", "Rafique", "Raihan", "Rakibul", "Rashedul", "Reza", "Riazul", 
    "Rokonuzzaman", "Ruhul", "Rumana", "Saad", "Sabbir", "Sabir", "Sadi", "Saiful", "Sajeeb", "Sajidur", "Sajjadur", 
    "Salman", "Samad", "Samir", "Sanjoy", "Sarwar", "Saud", "Sazzad", "Shahidul", "Shahed", "Shahedul", "Shahriar", 
    "Shakibul", "Shamimul", "Shariful", "Shaukat", "Sohail", "Sujan", "Sumon", "Suruj", "Syed", "Tajul", "Tamal", 
    "Tanveer", "Tariqul", "Taufiqur", "Tipu", "Toufique", "Touhidul", "Uzzal", "Wasim", "Yasinul", "Yunus", 
    "Zahirul", "Zakariah", "Zayed", "Ziaul", "Zillur", "Zubayer", "Zulfiqar"
]
